# inherit from the proprietary version
-include vendor/lge/gelato/BoardConfigVendor.mk

# Camera
USE_CAMERA_STUB := true

# CPU
TARGET_BOARD_PLATFORM := msm7k
TARGET_ARCH_VARIANT := armv7-a
TARGET_CPU_ABI := armeabi
TARGET_CPU_ABI2 := armeabi
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

# Target properties
TARGET_BOOTLOADER_BOARD_NAME := gelato
TARGET_OTA_ASSERT_DEVICE := gelato,VS700,VM701,LGL55C

# Target information
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_NO_RADIOIMAGE := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

# QCOM
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true

# GPS
# BOARD_USES_GPSSHIM := true
# BOARD_GPS_NEEDS_XTRA := true
# BOARD_GPS_LIBRARIES := libgps
# BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := gelato
# BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 6225

# Browser
JS_ENGINE := v8

# USB mass storage
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
BOARD_CUSTOM_USB_CONTROLLER := ../../device/lge/gelato/netd/UsbController.cpp

# Sensors
TARGET_USES_OLD_LIBSENSORS_HAL := true

# Audio
#BOARD_USES_GENERIC_AUDIO := false
BOARD_PREBUILT_LIBAUDIO := true
BUILD_WITH_FULL_STAGEFRIGHT := true
#TARGET_PROVIDES_LIBAUDIO := true 

# Graphics
TARGET_HARDWARE_3D := false
TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_SF_NEEDS_REAL_DIMENSIONS := true
BOARD_NO_RGBX_8888 := true
BOARD_EGL_CFG := device/lge/gelato/files/lib/egl/egl.cfg
BOARD_HAS_LIMITED_EGL := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
TARGET_PROVIDES_INIT_TARGET_RC := true

# WiFI
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
BOARD_WLAN_DEVICE := bcm4330
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/etc/wl/rtecdc.bin nvram_path=/system/etc/wl/nvram.txt"
WIFI_DRIVER_MODULE_NAME := "wireless"
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_FW_STA_PATH := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_AP_PATH := "/system/etc/wl/rtecdc-apsta.bin"
WIFI_DRIVER_HAS_LGE_SOFTAP := true
WPA_SUPPLICANT_VERSION := VER_0_6_X

# Kernel
BOARD_KERNEL_CMDLINE := mem=477M console=ttyMSM2,115200n8 androidboot.hardware=gelato
BOARD_KERNEL_BASE := 0x12200000
BOARD_KERNEL_PAGESIZE := 2048

# Appropriate defaults?
BOARD_FLASH_BLOCK_SIZE := 131072

#Straight Talk
ifeq ($(SUB_MODEL),LGL55C)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0aa00000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0d520000
endif

# Virgin Mobile
ifeq ($(SUB_MODEL),VM701)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x009e00000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x00b500000
endif

# Sprint
ifeq ($(SUB_MODEL),VS700)
    BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
    BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x09e80000
    BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0a4e0000
endif

#BOARD_HAS_NO_SELECT_BUTTON := true
# Use this flag if the board has a ext4 partition larger than 2gb
#BOARD_HAS_LARGE_FILESYSTEM := true

WITH_DEXPREOPT := false
WITH_JIT := true
ENABLE_JSC_JIT := true

#TARGET_PROVIDES_LIBRIL = vendor/lge/gelato/proprietary/system/lib/libril-qc-1.so

# FM Radio
#BOARD_HAVE_FM_RADIO := false
#BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

TARGET_SF_NEEDS_REAL_DIMENSIONS := true
